# Generated by Django 3.2.9 on 2021-11-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterclass',
            name='name_picture',
            field=models.CharField(max_length=180, null=True),
        ),
    ]
