# Generated by Django 3.2.9 on 2021-11-23 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0002_masterclass_name_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterclass_clients',
            name='master_class',
        ),
        migrations.RemoveField(
            model_name='masterclass_clients',
            name='picture_choice',
        ),
        migrations.AddField(
            model_name='masterclass_clients',
            name='date_mk',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='masterclass_clients',
            name='local',
            field=models.CharField(max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='masterclass_clients',
            name='price',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='masterclass_clients',
            name='time_mk',
            field=models.TimeField(default=datetime.time, null=True),
        ),
        migrations.AlterField(
            model_name='masterclass',
            name='date_mk',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='masterclass',
            name='name_picture',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='masterclass_clients',
            name='email_guest',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='masterclass_clients',
            name='name_picture',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='masterclass_clients',
            name='tel_guest',
            field=models.BigIntegerField(),
        ),
    ]
