# Generated by Django 3.2.9 on 2021-11-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0003_auto_20211123_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterclass_clients',
            name='mobil_code',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
