# Generated by Django 3.2.9 on 2022-01-07 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0004_masterclass_clients_mobil_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterclass',
            name='date_mk',
            field=models.DateField(default=datetime.date),
        ),
        migrations.AlterField(
            model_name='masterclass_clients',
            name='date_mk',
            field=models.DateField(verbose_name='Дата проведения мастер-класса'),
        ),
        migrations.AlterField(
            model_name='masterclass_clients',
            name='email_guest',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Ваш е-маил'),
        ),
        migrations.AlterField(
            model_name='masterclass_clients',
            name='local',
            field=models.CharField(max_length=50, verbose_name='Адрес провения мастер-класса'),
        ),
        migrations.AlterField(
            model_name='masterclass_clients',
            name='mobil_code',
            field=models.CharField(choices=[('+37533', '(33)'), ('+37544', '(44)'), ('+37529', '(29)'), ('+37525', '(25)')], max_length=6, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='masterclass_clients',
            name='name_guest',
            field=models.CharField(max_length=50, verbose_name='Ваше имя'),
        ),
        migrations.AlterField(
            model_name='masterclass_clients',
            name='name_picture',
            field=models.CharField(max_length=16, null=True, verbose_name='Название картины'),
        ),
        migrations.AlterField(
            model_name='masterclass_clients',
            name='price',
            field=models.CharField(max_length=20, verbose_name='Стоимость мастер-класса'),
        ),
        migrations.AlterField(
            model_name='masterclass_clients',
            name='tel_guest',
            field=models.CharField(max_length=7, verbose_name='Ваш номер телефона'),
        ),
        migrations.AlterField(
            model_name='masterclass_clients',
            name='time_mk',
            field=models.TimeField(verbose_name='Время проведения мастер-класса'),
        ),
    ]
